#!/bin/sh
#
# @name S500 
#
# @type Javier Herrera
#
# @maintainer Javier Herrera <javierandresh039@gmail.com>
#

. ${R}etc/init.d/rc.mc_defaults


param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.171
param set-default CA_ROTOR0_PY 0.169
param set-default CA_ROTOR0_KM 0.0157829
param set-default CA_ROTOR1_PX -0.171
param set-default CA_ROTOR1_PY -0.169
param set-default CA_ROTOR1_KM 0.0157829
param set-default CA_ROTOR2_PX 0.171
param set-default CA_ROTOR2_PY -0.169
param set-default CA_ROTOR2_KM -0.0157829
param set-default CA_ROTOR3_PX -0.171
param set-default CA_ROTOR3_PY 0.169
param set-default CA_ROTOR3_KM -0.0157829

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
