#!/bin/sh
#
# @name Windrobo
#
# @type Coax OctoCopter
#
# @Developer Asif Khan
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=windrobo}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1
# param set COM_RCL_EXCEPT 7 # we are ignoring RC failsafes
# param set EKF2_RNG_CTRL 0 # Don't use rangefinder in altitude fusion

param set-default CA_AIRFRAME 0
# param set-default MAV_TYPE 14
param set-default CA_ROTOR_COUNT 8

# Other parameters

#param set COM_RCL_EXCEPT 7 # we are ignoring RC failsafes
#param set EKF2_RNG_CTRL 0 # Don't use rangefinder in altitude fusion

#param set MPC_Z_P 2
#param set MC_ROLLRATE_K 1
#param set MC_ROLLRATE_D 0.0028
#param set MC_ROLLRATE_I 0.225

# param set MC_PITCHRATE_K 1
#param set MC_PITCHRATE_D 0.0038
# param set MC_PITCHRATE_I 0.225

# param set MC_YAWRATE_K 1
# param set MC_YAWRATE_I 0.18

param set-default CA_ROTOR0_PX 0.35  # rotor 0,1
param set-default CA_ROTOR0_PY 0.35
param set-default CA_ROTOR0_PZ 0.08
param set-default CA_ROTOR0_KM 0.077

 
param set-default CA_ROTOR1_PX 0.35 # rotor 1,2
param set-default CA_ROTOR1_PY -0.35
param set-default CA_ROTOR1_PZ 0.08
param set-default CA_ROTOR1_KM -0.077

param set-default CA_ROTOR2_PX -0.35 # rotor 2,3
param set-default CA_ROTOR2_PY -0.35
param set-default CA_ROTOR2_PZ 0.08
param set-default CA_ROTOR2_KM 0.077

param set-default CA_ROTOR3_PX -0.35 # rotor 3,4
param set-default CA_ROTOR3_PY 0.35
param set-default CA_ROTOR3_PZ 0.08
param set-default CA_ROTOR3_KM -0.077

param set-default CA_ROTOR4_PX 0.35 # rotor 4,5
param set-default CA_ROTOR4_PY -0.35
param set-default CA_ROTOR4_PZ 0
param set-default CA_ROTOR4_KM 0.077

param set-default CA_ROTOR5_PX 0.35 # rotor 5,6
param set-default CA_ROTOR5_PY 0.35
param set-default CA_ROTOR5_PZ 0
param set-default CA_ROTOR5_KM -0.077

param set-default CA_ROTOR6_PX -0.35 # rotor 6,7
param set-default CA_ROTOR6_PY 0.35
param set-default CA_ROTOR6_PZ 0
param set-default CA_ROTOR6_KM 0.077

param set-default CA_ROTOR7_PX -0.35 # rotor 7,8
param set-default CA_ROTOR7_PY -0.35
param set-default CA_ROTOR7_PZ 0
param set-default CA_ROTOR7_KM -0.077

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_FUNC7 107
param set-default SIM_GZ_EC_FUNC8 108

param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_MIN2 10
param set-default SIM_GZ_EC_MIN3 10
param set-default SIM_GZ_EC_MIN4 10
param set-default SIM_GZ_EC_MIN5 10
param set-default SIM_GZ_EC_MIN6 10
param set-default SIM_GZ_EC_MIN7 10
param set-default SIM_GZ_EC_MIN8 10

param set-default SIM_GZ_EC_MAX1 500
param set-default SIM_GZ_EC_MAX2 500
param set-default SIM_GZ_EC_MAX3 500
param set-default SIM_GZ_EC_MAX4 500
param set-default SIM_GZ_EC_MAX5 500
param set-default SIM_GZ_EC_MAX6 500
param set-default SIM_GZ_EC_MAX7 500
param set-default SIM_GZ_EC_MAX8 500

param set-default MPC_THR_HOVER 0.60