#!/bin/sh
#
# @name Tarot 680 SITL
#
# @type Hexarotor x
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 13

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0.34
param set-default CA_ROTOR0_KM -0.017
param set-default CA_ROTOR1_PX 0
param set-default CA_ROTOR1_PY -0.34
param set-default CA_ROTOR1_KM 0.017
param set-default CA_ROTOR2_PX 0.30939
param set-default CA_ROTOR2_PY -0.17866
param set-default CA_ROTOR2_KM -0.017
param set-default CA_ROTOR3_PX -0.30941
param set-default CA_ROTOR3_PY 0.17866
param set-default CA_ROTOR3_KM 0.017
param set-default CA_ROTOR4_PX 0.30939
param set-default CA_ROTOR4_PY 0.17866
param set-default CA_ROTOR4_KM 0.017
param set-default CA_ROTOR5_PX -0.30941
param set-default CA_ROTOR5_PY -0.17866
param set-default CA_ROTOR5_KM -0.017

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106

