#!/bin/sh
#
# @name Generic Octocopter X geometry
#
# @type Octorotor x
# @class Copter
#
# @maintainer Javier Herrera <javier.herrera@windrobo.com>
#
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=w_beta}

# MAV_TYPE_OCTOROTOR 14
param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 8
param set-default MAV_TYPE 14

### gz classic parameters
param set-default CA_ROTOR0_PX 0.35  # rotor 0,1
param set-default CA_ROTOR0_PY 0.35
param set-default CA_ROTOR0_PZ 0.08
param set-default CA_ROTOR0_KM 0.077
 
param set-default CA_ROTOR1_PX 0.35 # rotor 1,2
param set-default CA_ROTOR1_PY -0.35
param set-default CA_ROTOR1_PZ 0.08
param set-default CA_ROTOR1_KM -0.077

param set-default CA_ROTOR2_PX -0.35 # rotor 2,3
param set-default CA_ROTOR2_PY -0.35
param set-default CA_ROTOR2_PZ 0.08
param set-default CA_ROTOR2_KM 0.077

param set-default CA_ROTOR3_PX -0.35 # rotor 3,4
param set-default CA_ROTOR3_PY 0.35
param set-default CA_ROTOR3_PZ 0.08
param set-default CA_ROTOR3_KM -0.077

param set-default CA_ROTOR4_PX 0.35 # rotor 4,5
param set-default CA_ROTOR4_PY -0.35
param set-default CA_ROTOR4_PZ 0
param set-default CA_ROTOR4_KM 0.077

param set-default CA_ROTOR5_PX 0.35 # rotor 5,6
param set-default CA_ROTOR5_PY 0.35
param set-default CA_ROTOR5_PZ 0
param set-default CA_ROTOR5_KM -0.077

param set-default CA_ROTOR6_PX -0.35 # rotor 6,7
param set-default CA_ROTOR6_PY 0.35
param set-default CA_ROTOR6_PZ 0
param set-default CA_ROTOR6_KM 0.077

param set-default CA_ROTOR7_PX -0.35 # rotor 7,8
param set-default CA_ROTOR7_PY -0.35
param set-default CA_ROTOR7_PZ 0
param set-default CA_ROTOR7_KM -0.077

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_FUNC7 107
param set-default SIM_GZ_EC_FUNC8 108