networks:
  emp-network:

services:
  simulation:
    image: px4io/px4-dev-ros2-foxy:latest
    container_name: px4
    tty: true
    volumes:
      - ./:/src/PX4-Autopilot/:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    privileged: true
    networks:
      - emp-network
    environment:
      - DISPLAY=:0
  uxrce:
    build:
      context: .
      dockerfile: xrce.Dockerfile
    image: ubuntu-xrcedds-suite
    container_name: uxrcedds
    tty: true
    networks:
      - emp-network
  qgc:
    build:
      context: .
      dockerfile: qgc.Dockerfile
    container_name: qgroundcontrol
    environment:
      - DISPLAY=:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /dev:/dev
    privileged: true
    tty: true
    networks:
      - emp-network
  ros2:
    build: 
      context: .
      dockerfile: /home/windrobo/windrobo/windrobo_ws/ros2_gazebo.Dockerfile
    container_name: ros2
    tty: true
    networks:
      - emp-network
    environment:
      - LOCAL_USER_ID=$(id -u)
      - DISPLAY=:0
    volumes:
      - /home/windrobo/windrobo/windrobo_ws:/ros2
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    privileged: true